import Breadcrumb from '../components/Breadcrumb'
import ReflectionAgent from '../components/ReflectionAgent'

export default function Consciousness() {
    return (
        <div className="container">
            <Breadcrumb items={[
                { label: 'Home', to: '/' },
                { label: 'Consciousness' }
            ]} />

            <div className="section-header">
                <h2>✨ Active Consciousness</h2>
                <span style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                    Agentic insights, proactive reflections, and goal alignment.
                </span>
            </div>

            <div style={{ maxWidth: '900px', margin: '0 auto' }}>
                <ReflectionAgent />
            </div>

            <div className="card glassmorphism" style={{ marginTop: 'var(--space-xl)', padding: 'var(--space-xl)' }}>
                <h3 style={{ marginBottom: 'var(--space-md)' }}>🧭 About this Layer</h3>
                <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                    The Consciousness layer is a local-first intelligence artifact generated by your Nanobot.
                    During every repository update, Nanobot analyzes your latest thoughts and memories to
                    compute these proactive insights, which are then synced here for your review.
                </p>
            </div>
        </div>
    )
}
