import Breadcrumb from '../components/Breadcrumb'
import ReflectionAgent from '../components/ReflectionAgent'
import WisdomGraphWidget from '../components/WisdomGraphWidget'

export default function Consciousness() {
    return (
        <div className="container">
            <Breadcrumb items={[
                { label: 'Home', to: '/' },
                { label: 'Consciousness' }
            ]} />

            <div className="section-header">
                <h2>✨ Active Consciousness</h2>
                <span style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                    Agentic insights, proactive reflections, and goal alignment.
                </span>
            </div>

            <div className="card glassmorphism" style={{ marginBottom: 'var(--space-xl)', padding: 'var(--space-xl)' }}>
                <h3 style={{ marginBottom: 'var(--space-md)' }}>🧭 About this Layer</h3>
                <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                    The Consciousness layer is a local-first intelligence artifact generated by your Nanobot.
                    During every repository update, Nanobot analyzes your latest thoughts and memories to
                    compute these proactive insights, which are then synced here for your review.
                </p>
            </div>

            <div className="intelligence-grid">
                <div className="reflection-column">
                    <ReflectionAgent />
                </div>

                <div className="wisdom-column">
                    <div className="section-header" style={{ marginBottom: 'var(--space-md)' }}>
                        <h3>🌌 Wisdom Delta</h3>
                        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Focusing on recent thought connections.</p>
                    </div>
                    <WisdomGraphWidget mode="delta" height={500} />
                </div>
            </div>

            <style dangerouslySetInnerHTML={{
                __html: `
                .intelligence-grid {
                    display: grid;
                    grid-template-columns: 1fr 1.2fr;
                    gap: var(--space-xl);
                    align-items: start;
                }
                @media (max-width: 1024px) {
                    .intelligence-grid {
                        grid-template-columns: 1fr;
                    }
                }
            `}} />
        </div>
    )
}
